- hosts: all
  tasks:
   - package:
      name: "httpd"
      state: present

   - service:
      name: "httpd"
      state: started
      enabled: yes


   - firewalld:
      port: 80/tcp
      state: enabled
      permanent: yes


